import { Resend } from 'resend'
import { TIER_PRICING, TIER_LIMITS, TIER_LABEL, formatPrice, type TierID } from '@/lib/pricing-config'

let _resend: Resend | null = null
const resend = () => {
  if (!_resend) _resend = new Resend(process.env.RESEND_API_KEY!)
  return _resend
}

const FROM_EMAIL = 'PersonaLink <noreply@personalink.in>'
const APP_URL = process.env.NEXT_PUBLIC_APP_URL!

// Inbound human contact — support escalations and form leads — lands here.
// Deliberately separate from the ops/personal inbox (ADMIN_EMAIL, used by system
// alerts) so customer-facing mail can never fall back to a personal Gmail.
const CONTACT_INBOX = 'hello@personalink.in'

function inrAmountFor(plan: string): string {
  if (plan === 'starter' || plan === 'standard' || plan === 'pro') {
    return formatPrice('INR', TIER_PRICING[plan].INR.monthly)
  }
  return formatPrice('INR', TIER_PRICING.starter.INR.monthly)
}

export async function sendApprovalEmail({
  to,
  userName,
  postContent,
  approvalToken,
  scheduledAt,
}: {
  to: string
  userName: string
  postContent: string
  approvalToken: string
  scheduledAt?: string | null
}) {
  const approveUrl = `${APP_URL}/approve/${approvalToken}?action=approve`
  const rejectUrl = `${APP_URL}/approve/${approvalToken}?action=reject`

  const scheduleLabel = scheduledAt
    ? new Date(scheduledAt).toLocaleString('en-IN', {
        weekday: 'long', day: 'numeric', month: 'long',
        hour: '2-digit', minute: '2-digit', hour12: true,
        timeZone: 'Asia/Kolkata',
      })
    : null

  const scheduleBanner = scheduleLabel
    ? `<div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px;padding:14px 16px;margin-bottom:24px;display:flex;align-items:center;gap:12px;">
        <span style="font-size:18px;">📅</span>
        <div>
          <p style="margin:0;font-size:13px;font-weight:600;color:#1e40af;">Scheduled to post on</p>
          <p style="margin:0;font-size:14px;color:#1d4ed8;">${scheduleLabel} IST</p>
        </div>
      </div>`
    : ''

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: scheduleLabel
      ? `Approve your LinkedIn post — going live ${scheduleLabel} IST`
      : `Your LinkedIn post is ready for approval`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <span style="display:inline-block;line-height:1;white-space:nowrap;vertical-align:middle;">
            <img src="${APP_URL}/logo-mark.png" alt="" width="24" height="24" style="vertical-align:middle;display:inline-block;border:0;margin-right:8px;width:24px;height:24px;" />
            <img src="${APP_URL}/logo-text.png" alt="PersonaLink" height="22" style="vertical-align:middle;display:inline-block;border:0;height:22px;width:auto;" />
          </span>
        </div>
      </div>
    </div>

    <div style="padding:32px;">
      <h1 style="margin:0 0 8px;font-size:22px;font-weight:600;color:#0f172a;">Your post is ready, ${userName.split(' ')[0]}!</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:15px;">Review your AI-generated LinkedIn post below and approve or reject it.</p>

      ${scheduleBanner}

      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin-bottom:28px;">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:14px;">
          <div style="width:8px;height:8px;background:#0A66C2;border-radius:50%;"></div>
          <span style="font-size:12px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">LinkedIn Post Preview</span>
        </div>
        <p style="margin:0;color:#0f172a;font-size:15px;line-height:1.7;white-space:pre-wrap;">${postContent}</p>
      </div>

      <div style="display:flex;gap:12px;margin-bottom:24px;">
        <a href="${approveUrl}" style="flex:1;display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;">
          Approve &amp; Post
        </a>
        <a href="${rejectUrl}" style="flex:1;display:block;text-align:center;background:white;color:#64748b;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;border:1px solid #e2e8f0;">
          Reject
        </a>
      </div>

      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        This post was generated by PersonaLink AI. You can always edit it in your
        <a href="${APP_URL}/dashboard/posts" style="color:#0A66C2;">dashboard</a>.
      </p>
    </div>
  </div>
</body>
</html>
    `,
    text: `Your LinkedIn post is ready for approval!${scheduleLabel ? `\n\nScheduled: ${scheduleLabel} IST` : ''}\n\n${postContent}\n\nApprove: ${approveUrl}\nReject: ${rejectUrl}`,
  })
}

export async function sendWeeklyDigestEmail({
  to,
  userName,
  trendingTopics,
  postInsight,
  scheduledCount,
}: {
  to: string
  userName: string
  trendingTopics: Array<{ title: string; angle: string }>
  postInsight: string
  scheduledCount: number
}) {
  const firstName = userName.split(' ')[0]
  const topicsHtml = trendingTopics
    .map(
      (t, i) => `
    <div style="border-left:3px solid #0A66C2;padding:12px 16px;margin-bottom:12px;background:#f8fafc;border-radius:0 8px 8px 0;">
      <p style="margin:0 0 4px;font-weight:600;color:#0f172a;font-size:14px;">${i + 1}. ${t.title}</p>
      <p style="margin:0;color:#64748b;font-size:13px;">${t.angle}</p>
    </div>`
    )
    .join('')

  const scheduleNote =
    scheduledCount < 3
      ? `<div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:8px;padding:14px 16px;margin-bottom:24px;">
          <p style="margin:0;font-size:13px;color:#92400e;">You have <strong>${scheduledCount} post${scheduledCount !== 1 ? 's' : ''}</strong> scheduled this week. Aim for at least 3 for consistent growth.</p>
        </div>`
      : ''

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Your LinkedIn content ideas for this week, ${firstName}`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <span style="display:inline-block;line-height:1;white-space:nowrap;vertical-align:middle;">
            <img src="${APP_URL}/logo-mark.png" alt="" width="24" height="24" style="vertical-align:middle;display:inline-block;border:0;margin-right:8px;width:24px;height:24px;" />
            <img src="${APP_URL}/logo-text.png" alt="PersonaLink" height="22" style="vertical-align:middle;display:inline-block;border:0;height:22px;width:auto;" />
          </span>
        </div>
      </div>
      <p style="margin:16px 0 0;color:rgba(255,255,255,0.85);font-size:14px;">Your weekly content briefing</p>
    </div>

    <div style="padding:32px;">
      <h1 style="margin:0 0 6px;font-size:20px;font-weight:600;color:#0f172a;">Good morning, ${firstName}!</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:14px;">Here are 3 trending topics to post about this week.</p>

      ${scheduleNote}

      <h2 style="margin:0 0 14px;font-size:15px;font-weight:600;color:#0f172a;">Trending in your industry</h2>
      ${topicsHtml}

      <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:14px 16px;margin:24px 0;">
        <p style="margin:0 0 4px;font-size:12px;font-weight:600;color:#166534;text-transform:uppercase;letter-spacing:0.05em;">Your insight</p>
        <p style="margin:0;color:#15803d;font-size:14px;">${postInsight}</p>
      </div>

      <a href="${APP_URL}/dashboard/suggestions" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-bottom:16px;">
        See all suggestions →
      </a>

      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        Sent every Monday by <a href="${APP_URL}/dashboard" style="color:#0A66C2;">PersonaLink</a>.
        Your topics are refreshed every 6 hours.
      </p>
    </div>
  </div>
</body>
</html>`,
    text: `Your LinkedIn content ideas for this week\n\n${trendingTopics.map((t, i) => `${i + 1}. ${t.title}\n   ${t.angle}`).join('\n\n')}\n\n${postInsight}\n\nSee all suggestions: ${APP_URL}/dashboard/suggestions`,
  })
}

export async function sendImageBriefEmail({
  to,
  userName,
  prompts,
  month,
}: {
  to: string
  userName: string
  prompts: string[]
  month: string
}) {
  const firstName = userName.split(' ')[0]
  const promptsHtml = prompts
    .map((p, i) => `
    <div style="display:flex;gap:14px;padding:14px 0;border-bottom:1px solid #f1f5f9;align-items:flex-start;">
      <div style="width:28px;height:28px;background:#e8f0fb;border-radius:8px;display:flex;align-items:center;justify-content:center;font-weight:700;color:#0A66C2;font-size:13px;flex-shrink:0;">${i + 1}</div>
      <p style="margin:0;color:#374151;font-size:14px;line-height:1.6;">${p}</p>
    </div>`)
    .join('')

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Your LinkedIn photo brief for ${month}, ${firstName}`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <span style="display:inline-block;line-height:1;white-space:nowrap;vertical-align:middle;">
            <img src="${APP_URL}/logo-mark.png" alt="" width="24" height="24" style="vertical-align:middle;display:inline-block;border:0;margin-right:8px;width:24px;height:24px;" />
            <img src="${APP_URL}/logo-text.png" alt="PersonaLink" height="22" style="vertical-align:middle;display:inline-block;border:0;height:22px;width:auto;" />
          </span>
        </div>
      </div>
    </div>
    <div style="padding:32px;">
      <h1 style="margin:0 0 8px;font-size:20px;font-weight:700;color:#0f172a;">Your photo brief for ${month}</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:14px;">
        5 specific photos to shoot this month. Images boost LinkedIn engagement by up to 3×.
      </p>
      <div>${promptsHtml}</div>
      <div style="margin-top:24px;background:#fffbeb;border:1px solid #fcd34d;border-radius:10px;padding:14px 16px;">
        <p style="margin:0;font-size:13px;color:#92400e;">
          💡 Batch-shoot these in one session. Natural light, candid moments, real settings — not stock photo vibes.
        </p>
      </div>
      <a href="${APP_URL}/dashboard" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-top:24px;">
        Open Dashboard →
      </a>
    </div>
  </div>
</body>
</html>`,
    text: `Your LinkedIn photo brief for ${month}\n\n${prompts.map((p, i) => `${i + 1}. ${p}`).join('\n\n')}\n\n${APP_URL}/dashboard`,
  })
}

export async function sendWelcomeEmail({
  to,
  userName,
}: {
  to: string
  userName: string
}) {
  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Welcome to PersonaLink, ${userName.split(' ')[0]}!`,
    html: `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;padding:40px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <h1 style="color:#0f172a;font-size:22px;margin-bottom:16px;">Welcome aboard, ${userName.split(' ')[0]}!</h1>
    <p style="color:#374151;line-height:1.7;">Your LinkedIn account is connected. Here's how to get started:</p>
    <ol style="color:#374151;line-height:2;">
      <li>Set up your <a href="${APP_URL}/onboarding" style="color:#0A66C2;">content profile</a> — your role, topics, and writing style</li>
      <li>Generate your first post with AI</li>
      <li>Approve it via email or directly on the dashboard</li>
      <li>Schedule it to go live at the perfect time</li>
    </ol>
    <a href="${APP_URL}/onboarding" style="display:inline-block;margin-top:16px;background:#0A66C2;color:white;text-decoration:none;padding:14px 28px;border-radius:8px;font-weight:600;">Complete setup →</a>
  </div>
</body>
</html>
    `,
    text: `Welcome to PersonaLink, ${userName.split(' ')[0]}! Complete your setup: ${APP_URL}/onboarding`,
  })
}

export async function sendTrialStartedEmail({
  to,
  userName,
  trialEndsAt,
  plan,
}: {
  to: string
  userName: string
  trialEndsAt: Date
  plan: string
}) {
  const firstName = userName.split(' ')[0]
  const endsDate = trialEndsAt.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
  const amount = inrAmountFor(plan)
  const planLabel = TIER_LABEL[plan as TierID] ?? (plan.charAt(0).toUpperCase() + plan.slice(1))

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Your 7-day free trial has started, ${firstName}!`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <span style="display:inline-block;line-height:1;white-space:nowrap;vertical-align:middle;">
            <img src="${APP_URL}/logo-mark.png" alt="" width="24" height="24" style="vertical-align:middle;display:inline-block;border:0;margin-right:8px;width:24px;height:24px;" />
            <img src="${APP_URL}/logo-text.png" alt="PersonaLink" height="22" style="vertical-align:middle;display:inline-block;border:0;height:22px;width:auto;" />
          </span>
        </div>
      </div>
    </div>

    <div style="padding:32px;">
      <div style="background:#ecfdf5;border:1px solid #bbf7d0;border-radius:12px;padding:16px 20px;margin-bottom:24px;display:flex;align-items:center;gap:12px;">
        <div style="width:32px;height:32px;background:#059669;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
          <span style="color:white;font-size:16px;">✓</span>
        </div>
        <div>
          <p style="margin:0;font-weight:600;color:#065f46;font-size:14px;">7-day free trial activated</p>
          <p style="margin:0;color:#047857;font-size:13px;">You won't be charged until ${endsDate}</p>
        </div>
      </div>

      <h1 style="margin:0 0 8px;font-size:22px;font-weight:600;color:#0f172a;">Your trial has started, ${firstName}!</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:15px;">You have full access to the <strong>${planLabel}</strong> plan for the next 7 days — completely free.</p>

      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin-bottom:28px;">
        <h2 style="margin:0 0 14px;font-size:14px;font-weight:600;color:#0f172a;">Trial details</h2>
        <table style="width:100%;border-collapse:collapse;">
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Plan</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:#0f172a;font-size:14px;">${planLabel}</td>
          </tr>
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Trial ends</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:#0f172a;font-size:14px;">${endsDate}</td>
          </tr>
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">First charge</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:#0f172a;font-size:14px;">${amount}/mo on ${endsDate}</td>
          </tr>
        </table>
      </div>

      <p style="margin:0 0 20px;color:#64748b;font-size:14px;">Get started by generating your first LinkedIn post.</p>

      <a href="${APP_URL}/dashboard" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-bottom:16px;">
        Go to Dashboard →
      </a>

      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        You can cancel anytime before ${endsDate} — no charge.
        <a href="${APP_URL}/dashboard/settings?tab=plan" style="color:#0A66C2;">Manage subscription</a>
      </p>
    </div>
  </div>
</body>
</html>`,
    text: `Your 7-day free trial has started!\n\nPlan: ${planLabel}\nTrial ends: ${endsDate}\nFirst charge: ${amount}/mo on ${endsDate}\n\nYou have full access for 7 days. No charge until ${endsDate}.\n\nGo to dashboard: ${APP_URL}/dashboard`,
  })
}


export async function sendPipelineReminderEmail({
  to,
  userName,
  upcomingCount,
  postsUsed,
  postsLimit,
  plan,
}: {
  to: string
  userName: string
  upcomingCount: number
  postsUsed: number
  postsLimit: number
  plan: string
}) {
  const firstName = userName.split(' ')[0]
  const remaining = postsLimit - postsUsed
  const planLabel = plan.charAt(0).toUpperCase() + plan.slice(1)

  const urgencyColor = upcomingCount === 0 ? '#dc2626' : '#d97706'
  const urgencyBg = upcomingCount === 0 ? '#fef2f2' : '#fffbeb'
  const urgencyBorder = upcomingCount === 0 ? '#fca5a5' : '#fcd34d'
  const pipelineMessage =
    upcomingCount === 0
      ? `You have <strong>no posts scheduled</strong> — your LinkedIn presence will go quiet soon.`
      : `You only have <strong>${upcomingCount} post${upcomingCount !== 1 ? 's' : ''} left</strong> in your queue.`

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: upcomingCount === 0
      ? `Your LinkedIn queue is empty, ${firstName} — time to refill it`
      : `Your post queue is running low, ${firstName}`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <span style="display:inline-block;line-height:1;white-space:nowrap;vertical-align:middle;">
            <img src="${APP_URL}/logo-mark.png" alt="" width="24" height="24" style="vertical-align:middle;display:inline-block;border:0;margin-right:8px;width:24px;height:24px;" />
            <img src="${APP_URL}/logo-text.png" alt="PersonaLink" height="22" style="vertical-align:middle;display:inline-block;border:0;height:22px;width:auto;" />
          </span>
        </div>
      </div>
    </div>

    <div style="padding:32px;">
      <h1 style="margin:0 0 8px;font-size:22px;font-weight:600;color:#0f172a;">Keep the momentum going, ${firstName}</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:15px;">Consistent posting is what drives LinkedIn growth — here's a quick check-in on your queue.</p>

      <div style="background:${urgencyBg};border:1px solid ${urgencyBorder};border-radius:10px;padding:16px 18px;margin-bottom:24px;">
        <p style="margin:0;font-size:14px;color:${urgencyColor};">${pipelineMessage}</p>
      </div>

      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin-bottom:28px;">
        <h2 style="margin:0 0 14px;font-size:14px;font-weight:600;color:#0f172a;">Your ${planLabel} plan this month</h2>
        <table style="width:100%;border-collapse:collapse;">
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Posts generated</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:#0f172a;font-size:14px;">${postsUsed} / ${postsLimit}</td>
          </tr>
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Generations remaining</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:${remaining > 5 ? '#059669' : '#d97706'};font-size:14px;">${remaining}</td>
          </tr>
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Posts in queue</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:${upcomingCount > 0 ? '#0f172a' : '#dc2626'};font-size:14px;">${upcomingCount}</td>
          </tr>
        </table>
      </div>

      <a href="${APP_URL}/dashboard" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-bottom:16px;">
        Generate posts now →
      </a>

      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        You're on the ${planLabel} plan. Resets on the 1st of each month.<br>
        <a href="${APP_URL}/dashboard/settings?tab=plan" style="color:#0A66C2;">Manage subscription</a>
      </p>
    </div>
  </div>
</body>
</html>`,
    text: `Keep the momentum going, ${firstName}!\n\n${upcomingCount === 0 ? 'Your LinkedIn queue is empty.' : `You have ${upcomingCount} post${upcomingCount !== 1 ? 's' : ''} left in your queue.`}\n\nThis month: ${postsUsed}/${postsLimit} posts generated, ${remaining} remaining.\n\nGenerate posts now: ${APP_URL}/dashboard`,
  })
}

export async function sendSupportReply({
  to,
  subject,
  body,
  ticketNumber,
}: {
  to: string
  subject: string
  body: string
  ticketNumber: string
}) {
  const reSubject = subject.startsWith('Re:') ? subject : `Re: ${subject}`
  const footerHtml = `<div style="margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8;">Support ticket: <strong style="color:#64748b;">${ticketNumber}</strong> — Reply to this email to follow up.</div>`
  const footerText = `\n\n---\nSupport ticket: ${ticketNumber} — Reply to this email to follow up.`
  return resend().emails.send({
    from: 'PersonaLink Support <support@personalink.in>',
    to,
    subject: reSubject,
    text: body + footerText,
    html: `<div style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#0f172a;line-height:1.7;font-size:15px;">${body.split('\n').map(l => `<p style="margin:0 0 12px;">${l}</p>`).join('')}${footerHtml}</div>`,
  })
}

export async function sendEscalationEmail({
  originalFrom,
  subject,
  originalBody,
  aiDraft,
  userContext,
  escalationReason,
  confidence,
  ticketNumber,
}: {
  originalFrom: string
  subject: string
  originalBody: string
  aiDraft: string
  userContext: string
  escalationReason: string | null
  confidence: number
  ticketNumber: string
}) {
  const confidencePct = Math.round(confidence * 100)

  return resend().emails.send({
    from: 'PersonaLink Support <support@personalink.in>',
    to: CONTACT_INBOX,
    replyTo: originalFrom,
    subject: `[SUPPORT] ${ticketNumber} — ${subject}`,
    html: `
<div style="font-family:system-ui,sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#0f172a;font-size:14px;line-height:1.6;">

  <div style="background:#fef3c7;border:1px solid #fcd34d;border-radius:8px;padding:12px 16px;margin-bottom:20px;color:#92400e;">
    <strong>${ticketNumber}</strong> &nbsp;·&nbsp; AI confidence: ${confidencePct}%${escalationReason ? ` — ${escalationReason}` : ''}
    <br><span style="font-size:12px;">Hit Reply to respond directly to ${originalFrom}</span>
  </div>

  <div style="background:#f1f5f9;border-radius:8px;padding:14px 16px;margin-bottom:20px;font-family:monospace;font-size:13px;white-space:pre-wrap;">${userContext}</div>

  <p style="margin:0 0 6px;font-size:12px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">Original email</p>
  <div style="border-left:3px solid #e2e8f0;padding:12px 16px;margin-bottom:20px;color:#374151;white-space:pre-wrap;">${originalBody}</div>

  ${aiDraft ? `
  <p style="margin:0 0 6px;font-size:12px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">AI draft (edit before sending)</p>
  <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:14px 16px;white-space:pre-wrap;color:#166534;">${aiDraft}</div>
  ` : ''}

</div>`,
    text: `${ticketNumber} · AI confidence: ${confidencePct}%${escalationReason ? ` — ${escalationReason}` : ''}\nReply to this email to respond directly to ${originalFrom}.\n\n--- USER CONTEXT ---\n${userContext}\n\n--- ORIGINAL EMAIL ---\n${originalBody}${aiDraft ? `\n\n--- AI DRAFT (edit before sending) ---\n${aiDraft}` : ''}`,
  })
}

export async function sendAdminAlert({ subject, body }: { subject: string; body: string }) {
  const adminEmail = process.env.ADMIN_EMAIL || 'hamzabamboat@gmail.com'
  return resend().emails.send({
    from: FROM_EMAIL,
    to: adminEmail,
    subject,
    html: `<div style="font-family:monospace;white-space:pre-wrap;padding:24px;background:#f8fafc;border-radius:8px;">${body}</div>`,
    text: body,
  })
}

/* ─────────────────────────────────────────────
 * Quota-aware lifecycle emails
 * ─────────────────────────────────────────────
 * These derive copy from lib/pricing-config so quotas stay correct
 * as the tier table changes. They are library-only — wire up triggers
 * (cron or webhook) when needed.
 */

export async function sendQuotaWarningEmail({
  to,
  userName,
  plan,
  used,
  limit,
}: {
  to: string
  userName: string
  plan: TierID
  used: number
  limit: number
}) {
  const { getNextTier, getTierLimits } = await import('@/lib/pricing-config')
  const firstName = userName.split(' ')[0]
  const nextTier = getNextTier(plan)
  const nextLimit = nextTier ? getTierLimits(nextTier).postsPerMonth : null
  const cta = nextTier && nextLimit != null
    ? `Upgrade to ${TIER_LABEL[nextTier]} for ${nextLimit} posts`
    : `Manage your plan`

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `You're close to your monthly limit`,
    html: `<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
      <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;padding:36px;">
        <h1 style="color:#0f172a;font-size:20px;margin:0 0 8px;">Heads up, ${firstName}</h1>
        <p style="color:#475569;font-size:14px;line-height:1.6;margin:0 0 16px;">
          You've used <strong>${used} of ${limit}</strong> post generations on the ${TIER_LABEL[plan]} plan this month.
          You have <strong>${Math.max(0, limit - used)} left</strong> before reset on the 1st.
        </p>
        <a href="${APP_URL}/dashboard/upgrade" style="display:inline-block;background:#0A66C2;color:white;text-decoration:none;padding:12px 22px;border-radius:8px;font-weight:600;font-size:14px;">${cta} →</a>
      </div></body></html>`,
    text: `You've used ${used} of ${limit} posts this month on the ${TIER_LABEL[plan]} plan. ${cta}: ${APP_URL}/dashboard/upgrade`,
  })
}

export async function sendQuotaReachedEmail({
  to,
  userName,
  plan,
  limit,
}: {
  to: string
  userName: string
  plan: TierID
  limit: number
}) {
  const { getNextTier, getTierLimits } = await import('@/lib/pricing-config')
  const firstName = userName.split(' ')[0]
  const nextTier = getNextTier(plan)
  const nextLimit = nextTier ? getTierLimits(nextTier).postsPerMonth : null
  const cta = nextTier && nextLimit != null
    ? `Upgrade to ${TIER_LABEL[nextTier]} (${nextLimit} posts)`
    : `Manage your plan`

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Out of posts? Upgrade in 30 seconds`,
    html: `<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
      <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;padding:36px;">
        <h1 style="color:#0f172a;font-size:20px;margin:0 0 8px;">You've hit your monthly limit, ${firstName}</h1>
        <p style="color:#475569;font-size:14px;line-height:1.6;margin:0 0 16px;">
          ${limit} of ${limit} posts used on the ${TIER_LABEL[plan]} plan. Quotas reset on the 1st of every month —
          or you can upgrade now and pick up where you left off in 30 seconds.
        </p>
        <a href="${APP_URL}/dashboard/upgrade" style="display:inline-block;background:#0A66C2;color:white;text-decoration:none;padding:12px 22px;border-radius:8px;font-weight:600;font-size:14px;">${cta} →</a>
      </div></body></html>`,
    text: `You've hit your ${limit}-post limit on the ${TIER_LABEL[plan]} plan. ${cta}: ${APP_URL}/dashboard/upgrade`,
  })
}

export async function sendUpgradeConfirmationEmail({
  to,
  userName,
  plan,
}: {
  to: string
  userName: string
  plan: TierID
}) {
  const { getTierLimits } = await import('@/lib/pricing-config')
  const firstName = userName.split(' ')[0]
  const limits = getTierLimits(plan)
  const posts = limits.postsPerMonth == null ? 'unlimited' : `${limits.postsPerMonth}`
  const fingerprints = limits.voiceFingerprints == null ? 'unlimited' : `${limits.voiceFingerprints}`

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Welcome to PersonaLink ${TIER_LABEL[plan]}`,
    html: `<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
      <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;padding:36px;">
        <h1 style="color:#0f172a;font-size:22px;margin:0 0 8px;">You're on ${TIER_LABEL[plan]}, ${firstName} 🎉</h1>
        <p style="color:#475569;font-size:14px;line-height:1.6;margin:0 0 20px;">
          Your new plan unlocks <strong>${posts} posts per month</strong> and
          <strong>${fingerprints} voice fingerprint${fingerprints === '1' ? '' : 's'}</strong>.
          Quota resets on the 1st of each month — manage billing anytime from Settings.
        </p>
        <a href="${APP_URL}/dashboard" style="display:inline-block;background:#0A66C2;color:white;text-decoration:none;padding:12px 22px;border-radius:8px;font-weight:600;font-size:14px;">Open dashboard →</a>
      </div></body></html>`,
    text: `Welcome to PersonaLink ${TIER_LABEL[plan]}. You now have ${posts} posts/month and ${fingerprints} voice fingerprint${fingerprints === '1' ? '' : 's'}.`,
  })
}

export async function sendDowngradeConfirmationEmail({
  to,
  userName,
  plan,
  effectiveDate,
}: {
  to: string
  userName: string
  plan: TierID
  effectiveDate: Date
}) {
  const { getTierLimits } = await import('@/lib/pricing-config')
  const firstName = userName.split(' ')[0]
  const dateLabel = effectiveDate.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
  const limits = getTierLimits(plan)
  const posts = limits.postsPerMonth == null ? 'unlimited' : `${limits.postsPerMonth}`

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Your plan will change to ${TIER_LABEL[plan]} on ${dateLabel}`,
    html: `<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
      <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;padding:36px;">
        <h1 style="color:#0f172a;font-size:20px;margin:0 0 8px;">Plan change scheduled, ${firstName}</h1>
        <p style="color:#475569;font-size:14px;line-height:1.6;margin:0 0 16px;">
          Your plan will switch to <strong>${TIER_LABEL[plan]}</strong> on <strong>${dateLabel}</strong>.
          From that date you'll have <strong>${posts} posts per month</strong>. You can re-upgrade anytime
          before then to cancel the change.
        </p>
        <a href="${APP_URL}/dashboard/settings?tab=plan" style="display:inline-block;background:#0A66C2;color:white;text-decoration:none;padding:12px 22px;border-radius:8px;font-weight:600;font-size:14px;">Manage plan →</a>
      </div></body></html>`,
    text: `Your plan will change to ${TIER_LABEL[plan]} on ${dateLabel} (${posts} posts/month).`,
  })
}

/* ─────────────────────────────────────────────
 * Agency inquiry funnel — /for-agencies
 * ───────────────────────────────────────────── */

export type AgencyInquiryRecord = {
  id: string
  agency_name: string
  owner_name: string
  owner_role: string | null
  email: string
  phone: string | null
  website: string | null
  linkedin_url: string | null
  client_count: string
  current_tools: string[] | null
  primary_problem: string | null
  preferred_currency: string | null
  timeline: string | null
  source: string | null
  ip: string | null
  user_agent: string | null
  submitted_at: string
}

function escapeAgencyHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export async function sendAgencyInquiryAdminAlert(record: AgencyInquiryRecord) {
  const adminEmail =
    process.env.AGENCY_INQUIRY_ADMIN_EMAIL || CONTACT_INBOX

  const row = (label: string, value: string | null | undefined) =>
    value
      ? `<tr><td style="padding:6px 14px 6px 0;color:#64748b;font-size:13px;white-space:nowrap;vertical-align:top;">${label}</td><td style="padding:6px 0;color:#0f172a;font-size:14px;">${escapeAgencyHtml(value)}</td></tr>`
      : ''

  const tools = record.current_tools?.length ? record.current_tools.join(', ') : null

  return resend().emails.send({
    from: FROM_EMAIL,
    to: adminEmail,
    replyTo: record.email,
    subject: `Agency inquiry — ${record.agency_name} (${record.client_count} clients)`,
    html: `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:24px;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;padding:28px;border:1px solid #e2e8f0;">
    <h1 style="margin:0 0 4px;font-size:18px;color:#0f172a;font-weight:600;">Agency inquiry</h1>
    <p style="margin:0 0 20px;color:#64748b;font-size:13px;">Reply within 24h.</p>
    <table style="width:100%;border-collapse:collapse;">
      ${row('Agency', record.agency_name)}
      ${row('Contact', record.owner_name)}
      ${row('Role', record.owner_role)}
      ${row('Email', record.email)}
      ${row('Phone', record.phone)}
      ${row('Website', record.website)}
      ${row('LinkedIn', record.linkedin_url)}
      ${row('Clients', record.client_count)}
      ${row('Currently using', tools)}
      ${row('#1 problem', record.primary_problem)}
      ${row('Preferred currency', record.preferred_currency)}
      ${row('Timeline', record.timeline)}
      ${row('Source', record.source)}
    </table>
    <hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0;" />
    <p style="margin:0;color:#94a3b8;font-size:11px;font-family:monospace;">
      id ${record.id} · ${new Date(record.submitted_at).toISOString()}<br/>
      ip ${record.ip ?? '-'} · ua ${escapeAgencyHtml((record.user_agent ?? '').slice(0, 80))}
    </p>
  </div>
</body>
</html>`,
    text: [
      `Agency inquiry — ${record.agency_name} (${record.client_count} clients)`,
      '',
      `Agency: ${record.agency_name}`,
      `Contact: ${record.owner_name} (${record.owner_role ?? '-'})`,
      `Email: ${record.email}`,
      `Phone: ${record.phone ?? '-'}`,
      `Website: ${record.website ?? '-'}`,
      `LinkedIn: ${record.linkedin_url ?? '-'}`,
      `Clients: ${record.client_count}`,
      `Currently using: ${tools ?? '-'}`,
      `#1 problem: ${record.primary_problem ?? '-'}`,
      `Preferred currency: ${record.preferred_currency ?? '-'}`,
      `Timeline: ${record.timeline ?? '-'}`,
      `Source: ${record.source ?? '-'}`,
      '',
      `id: ${record.id}`,
      `submitted_at: ${record.submitted_at}`,
      `ip: ${record.ip ?? '-'}`,
    ].join('\n'),
  })
}

/* ─────────────────────────────────────────────
 * Affiliate program — /affiliate/apply + /admin/affiliates
 * ─────────────────────────────────────────────
 * Four envelopes:
 *   1. sendAffiliateApplicationAdminAlert   — ping admin on new application
 *   2. sendAffiliateApplicationAutoReply    — confirm submit to applicant
 *   3. sendAffiliateApprovedEmail           — applicant gets ref code + dashboard link
 *   4. sendAffiliateRejectedEmail           — applicant gets reason + path forward
 * All are best-effort; callers wrap them in Promise.allSettled / .catch.
 */

export type AffiliateApplicationRecord = {
  id: string
  user_id: string
  full_name: string
  email: string
  ref_code: string
  audience_size: string | null
  audience_description: string | null
  promotion_channels: string[] | null
  website_url: string | null
  linkedin_url: string | null
  payout_method: string | null
  payout_details: Record<string, unknown> | null
  applied_at: string
}

export async function sendAffiliateApplicationAdminAlert(record: AffiliateApplicationRecord) {
  const adminEmail =
    process.env.AFFILIATE_ADMIN_EMAIL || CONTACT_INBOX

  const row = (label: string, value: string | null | undefined) =>
    value
      ? `<tr><td style="padding:6px 14px 6px 0;color:#64748b;font-size:13px;white-space:nowrap;vertical-align:top;">${label}</td><td style="padding:6px 0;color:#0f172a;font-size:14px;">${escapeAgencyHtml(value)}</td></tr>`
      : ''

  const channels = record.promotion_channels?.length ? record.promotion_channels.join(', ') : null
  const payoutRaw = (record.payout_details as { raw?: string } | null)?.raw ?? null
  const reviewUrl = `${APP_URL}/admin/affiliates`

  return resend().emails.send({
    from: FROM_EMAIL,
    to: adminEmail,
    replyTo: record.email,
    subject: `Affiliate application — ${record.full_name} (${record.audience_size ?? 'audience ?'})`,
    html: `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:24px;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;padding:28px;border:1px solid #e2e8f0;">
    <h1 style="margin:0 0 4px;font-size:18px;color:#0f172a;font-weight:600;">Affiliate application</h1>
    <p style="margin:0 0 20px;color:#64748b;font-size:13px;">Review in the admin panel within 1 working day.</p>
    <table style="width:100%;border-collapse:collapse;">
      ${row('Name', record.full_name)}
      ${row('Email', record.email)}
      ${row('Ref code', record.ref_code)}
      ${row('Audience', record.audience_size)}
      ${row('Channels', channels)}
      ${row('Website', record.website_url)}
      ${row('LinkedIn', record.linkedin_url)}
      ${row('Payout', record.payout_method)}
      ${row('Payout details', payoutRaw)}
    </table>
    ${record.audience_description ? `
    <div style="margin-top:18px;padding:14px 16px;background:#f1f5f9;border-radius:8px;color:#0f172a;font-size:14px;line-height:1.6;white-space:pre-wrap;">${escapeAgencyHtml(record.audience_description)}</div>
    ` : ''}
    <a href="${reviewUrl}" style="display:inline-block;margin-top:20px;background:#0A66C2;color:white;text-decoration:none;padding:12px 22px;border-radius:8px;font-weight:600;font-size:14px;">Open admin → review</a>
    <hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0;" />
    <p style="margin:0;color:#94a3b8;font-size:11px;font-family:monospace;">
      id ${record.id} · user ${record.user_id}<br/>
      applied ${new Date(record.applied_at).toISOString()}
    </p>
  </div>
</body>
</html>`,
    text: [
      `Affiliate application — ${record.full_name}`,
      '',
      `Name: ${record.full_name}`,
      `Email: ${record.email}`,
      `Ref code: ${record.ref_code}`,
      `Audience: ${record.audience_size ?? '-'}`,
      `Channels: ${channels ?? '-'}`,
      `Website: ${record.website_url ?? '-'}`,
      `LinkedIn: ${record.linkedin_url ?? '-'}`,
      `Payout: ${record.payout_method ?? '-'} ${payoutRaw ? `(${payoutRaw})` : ''}`,
      '',
      record.audience_description ? `Audience description:\n${record.audience_description}` : '',
      '',
      `Review: ${reviewUrl}`,
      `id: ${record.id}`,
    ].filter(Boolean).join('\n'),
  })
}

export async function sendAffiliateApplicationAutoReply(params: {
  to: string
  firstName: string
}) {
  const { to, firstName } = params
  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    replyTo: 'partners@personalink.in',
    subject: `Got your affiliate application`,
    html: `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:32px 16px;background:#fafaf7;font-family:system-ui,-apple-system,sans-serif;color:#1a1a1a;line-height:1.6;">
  <div style="max-width:520px;margin:0 auto;background:#fff;border-radius:12px;padding:32px;border:1px solid #e7e5df;">
    <p style="margin:0 0 16px;font-size:15px;">Hi ${escapeAgencyHtml(firstName)},</p>
    <p style="margin:0 0 16px;font-size:15px;">
      Thanks for applying to the Personalink affiliate program. I review every application personally — you'll hear back within one working day with either an approval (and your unique referral link) or some follow-up questions.
    </p>
    <p style="margin:0 0 16px;font-size:15px;">
      In the meantime, if there's anything specific about your audience you'd like me to know — or if you'd prefer a custom co-branded discount instead of a higher commission split — just reply to this email.
    </p>
    <p style="margin:24px 0 0;font-size:15px;color:#475569;">— Hamza, PersonaLink</p>
  </div>
  <p style="max-width:520px;margin:16px auto 0;font-size:11px;color:#94a3b8;text-align:center;">
    You received this because you applied at personalink.in/affiliate/apply.
  </p>
</body>
</html>`,
    text: [
      `Hi ${firstName},`,
      '',
      `Thanks for applying to the Personalink affiliate program. I review every application personally — you'll hear back within one working day with either an approval (and your unique referral link) or some follow-up questions.`,
      '',
      `In the meantime, if there's anything specific about your audience you'd like me to know — or if you'd prefer a custom co-branded discount instead of a higher commission split — just reply to this email.`,
      '',
      '— Hamza, PersonaLink',
    ].join('\n'),
  })
}

export async function sendAffiliateApprovedEmail(params: {
  to: string
  firstName: string
  refCode: string
}) {
  const { to, firstName, refCode } = params
  const shareLink = `${APP_URL}/?ref=${encodeURIComponent(refCode)}`
  const dashboardUrl = `${APP_URL}/affiliate/dashboard`

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    replyTo: 'partners@personalink.in',
    subject: `You're in — Personalink affiliate program 🎉`,
    html: `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
        <span style="display:inline-block;line-height:1;white-space:nowrap;vertical-align:middle;">
          <img src="${APP_URL}/logo-mark.png" alt="" width="24" height="24" style="vertical-align:middle;display:inline-block;border:0;margin-right:8px;width:24px;height:24px;" />
          <img src="${APP_URL}/logo-text.png" alt="PersonaLink" height="22" style="vertical-align:middle;display:inline-block;border:0;height:22px;width:auto;" />
        </span>
      </div>
    </div>

    <div style="padding:32px;">
      <h1 style="margin:0 0 8px;font-size:22px;font-weight:600;color:#0f172a;">You're approved, ${escapeAgencyHtml(firstName)}!</h1>
      <p style="margin:0 0 22px;color:#64748b;font-size:15px;">
        27.5% commission on every paid month for 12 months, on every customer you send. Here's everything you need to start.
      </p>

      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:18px 20px;margin-bottom:20px;">
        <p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">Your referral code</p>
        <p style="margin:0 0 14px;font-size:18px;font-weight:700;color:#0f172a;font-family:monospace;">${escapeAgencyHtml(refCode)}</p>
        <p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">Your share link</p>
        <p style="margin:0;font-size:13px;color:#0f172a;font-family:monospace;word-break:break-all;">${escapeAgencyHtml(shareLink)}</p>
      </div>

      <a href="${dashboardUrl}" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-bottom:24px;">
        Open partner dashboard →
      </a>

      <h2 style="margin:0 0 8px;font-size:14px;font-weight:600;color:#0f172a;">How it works from here</h2>
      <ol style="margin:0 0 8px;padding-left:20px;color:#475569;font-size:14px;line-height:1.7;">
        <li>Share your link wherever you write — newsletter, LinkedIn, blog, podcast notes.</li>
        <li>Anyone who signs up via that link within 30 days is attributed to you.</li>
        <li>When they start paying, commissions accrue in your dashboard. Request a payout once you cross ₹4,000.</li>
      </ol>

      <p style="margin:24px 0 0;font-size:13px;color:#94a3b8;">
        Reply to this email if you have questions — or want help with positioning, custom landing pages, or co-marketing.
      </p>
    </div>
  </div>
</body>
</html>`,
    text: [
      `You're approved, ${firstName}!`,
      '',
      `27.5% commission on every paid month for 12 months, on every customer you send.`,
      '',
      `Your referral code: ${refCode}`,
      `Your share link:   ${shareLink}`,
      '',
      `Partner dashboard: ${dashboardUrl}`,
      '',
      `How it works from here:`,
      `1. Share your link wherever you write — newsletter, LinkedIn, blog, podcast notes.`,
      `2. Anyone who signs up via that link within 30 days is attributed to you.`,
      `3. When they start paying, commissions accrue in your dashboard. Request a payout once you cross ₹4,000.`,
      '',
      `Reply to this email if you have questions or want help with positioning, custom landing pages, or co-marketing.`,
      '— Hamza, PersonaLink',
    ].join('\n'),
  })
}

export async function sendAffiliateRejectedEmail(params: {
  to: string
  firstName: string
  reason: string | null
}) {
  const { to, firstName, reason } = params
  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    replyTo: 'partners@personalink.in',
    subject: `An update on your Personalink affiliate application`,
    html: `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:32px 16px;background:#fafaf7;font-family:system-ui,-apple-system,sans-serif;color:#1a1a1a;line-height:1.6;">
  <div style="max-width:520px;margin:0 auto;background:#fff;border-radius:12px;padding:32px;border:1px solid #e7e5df;">
    <p style="margin:0 0 16px;font-size:15px;">Hi ${escapeAgencyHtml(firstName)},</p>
    <p style="margin:0 0 16px;font-size:15px;">
      Thanks for applying to the Personalink affiliate program. After reviewing your application I'm not able to approve you for the program right now.
    </p>
    ${reason ? `
    <div style="margin:0 0 16px;padding:14px 16px;background:#fef3c7;border-left:3px solid #d97706;border-radius:6px;color:#78350f;font-size:14px;">
      ${escapeAgencyHtml(reason)}
    </div>
    ` : ''}
    <p style="margin:0 0 16px;font-size:15px;">
      This isn't necessarily permanent — audiences grow, channels mature, and we re-review every quarter. If anything material changes (new newsletter, bigger LinkedIn following, a new niche fit), just reply to this email and I'll take another look.
    </p>
    <p style="margin:24px 0 0;font-size:15px;color:#475569;">— Hamza, PersonaLink</p>
  </div>
</body>
</html>`,
    text: [
      `Hi ${firstName},`,
      '',
      `Thanks for applying to the Personalink affiliate program. After reviewing your application I'm not able to approve you for the program right now.`,
      '',
      reason ? `Reason: ${reason}\n` : '',
      `This isn't necessarily permanent — audiences grow, channels mature, and we re-review every quarter. If anything material changes (new newsletter, bigger LinkedIn following, a new niche fit), just reply to this email and I'll take another look.`,
      '',
      '— Hamza, PersonaLink',
    ].filter(Boolean).join('\n'),
  })
}

export async function sendAgencyInquiryAutoReply(params: {
  to: string
  firstName: string
  agencyName: string
  clientCount: string
}) {
  const { to, firstName, agencyName, clientCount } = params

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    replyTo: 'hello@personalink.in',
    subject: `Got your inquiry — ${agencyName}`,
    html: `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:32px 16px;background:#fafaf7;font-family:system-ui,-apple-system,sans-serif;color:#1a1a1a;line-height:1.6;">
  <div style="max-width:520px;margin:0 auto;background:#fff;border-radius:12px;padding:32px;border:1px solid #e7e5df;">
    <p style="margin:0 0 16px;font-size:15px;">Hi ${escapeAgencyHtml(firstName)},</p>
    <p style="margin:0 0 16px;font-size:15px;">
      Thanks for the note about ${escapeAgencyHtml(agencyName)}. I will review your details and reply within 24 hours with next steps tailored to your setup (${escapeAgencyHtml(clientCount)} clients).
    </p>
    <p style="margin:24px 0 0;font-size:15px;color:#475569;">— Hamza, PersonaLink</p>
  </div>
  <p style="max-width:520px;margin:16px auto 0;font-size:11px;color:#94a3b8;text-align:center;">
    You received this because you submitted an inquiry at personalink.in/for-agencies.
  </p>
</body>
</html>`,
    text: [
      `Hi ${firstName},`,
      '',
      `Thanks for the note about ${agencyName}. I will review your details and reply within 24 hours with next steps tailored to your setup (${clientCount} clients).`,
      '',
      '— Hamza, PersonaLink',
    ].join('\n'),
  })
}

/* ─────────────────────────────────────────────
 * Value-first onboarding emails
 * ─────────────────────────────────────────────
 * Magic-link, welcome, day-2 nudge, day-7 stats.
 */

export async function sendMagicLinkEmail({ to, verifyUrl }: { to: string; verifyUrl: string }) {
  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: 'Your PersonaLink sign-in link',
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px;color:#0f172a">
        <h1 style="font-size:20px;margin:0 0 12px">Your voice is ready.</h1>
        <p style="font-size:15px;line-height:1.6;color:#334155;margin:0 0 20px">
          Click below to open your PersonaLink account — your voice fingerprint is already loaded.
        </p>
        <a href="${verifyUrl}" style="display:inline-block;background:#0A66C2;color:#fff;font-weight:600;
          font-size:15px;padding:12px 20px;border-radius:10px;text-decoration:none">Open my account →</a>
        <p style="font-size:12px;color:#94a3b8;margin:24px 0 0">This link expires in 15 minutes and can be used once.</p>
      </div>`,
  })
}

export async function sendEmailSignupWelcomeEmail({ to }: { to: string }) {
  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: 'Welcome to PersonaLink — generate your first post',
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px;color:#0f172a">
        <h1 style="font-size:20px;margin:0 0 12px">You're in.</h1>
        <p style="font-size:15px;line-height:1.6;color:#334155;margin:0 0 20px">
          Your voice fingerprint is saved. Generate your first post in your own voice — it takes about a minute.
        </p>
        <a href="${APP_URL}/welcome" style="display:inline-block;background:#0A66C2;color:#fff;font-weight:600;
          font-size:15px;padding:12px 20px;border-radius:10px;text-decoration:none">Generate my first post →</a>
      </div>`,
  })
}

export async function sendDay2NudgeEmail({ to, userName }: { to: string; userName: string }) {
  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: 'Your voice is waiting — post #2 in a minute',
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px;color:#0f172a">
        <h1 style="font-size:20px;margin:0 0 12px">Hey ${userName},</h1>
        <p style="font-size:15px;line-height:1.6;color:#334155;margin:0 0 20px">
          You generated a post in your voice. Keep the streak going — your next one is one click away.
        </p>
        <a href="${APP_URL}/dashboard" style="display:inline-block;background:#0A66C2;color:#fff;font-weight:600;
          font-size:15px;padding:12px 20px;border-radius:10px;text-decoration:none">Write another →</a>
      </div>`,
  })
}

export async function sendDay7StatsEmail({
  to, userName, postsGenerated,
}: { to: string; userName: string; postsGenerated: number }) {
  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: 'Your first week on PersonaLink',
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px;color:#0f172a">
        <h1 style="font-size:20px;margin:0 0 12px">One week in, ${userName}.</h1>
        <p style="font-size:15px;line-height:1.6;color:#334155;margin:0 0 8px">
          You've generated <strong>${postsGenerated}</strong> post${postsGenerated === 1 ? '' : 's'} in your voice so far.
        </p>
        <p style="font-size:15px;line-height:1.6;color:#334155;margin:0 0 20px">
          Upgrade to Starter for 12 posts/month, scheduling, and no watermark.
        </p>
        <a href="${APP_URL}/upgrade" style="display:inline-block;background:#0A66C2;color:#fff;font-weight:600;
          font-size:15px;padding:12px 20px;border-radius:10px;text-decoration:none">See plans →</a>
      </div>`,
  })
}

import type { GrowthReportBody } from '@/lib/growth-report'

export async function sendGrowthReportEmail({
  to, subject, body,
}: { to: string; subject: string; body: GrowthReportBody }) {
  const accentByTrend: Record<string, string> = {
    up: '#059669', flat: '#0A66C2', down: '#d97706', insufficient: '#64748b',
  }
  const accent = accentByTrend[body.trend] ?? '#0A66C2'
  const attributionHtml = body.attribution
    ? `<p style="margin:0 0 14px;font-size:15px;line-height:1.7;color:#334155;">${body.attribution}</p>`
    : ''
  const recoveryHtml = body.recovery
    ? `<div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:8px;padding:14px 16px;margin:0 0 20px;"><p style="margin:0;font-size:14px;color:#92400e;">${body.recovery}</p></div>`
    : ''

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <div style="background:#0A66C2;padding:28px 32px;">
      <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
        <span style="display:inline-block;line-height:1;white-space:nowrap;vertical-align:middle;">
          <img src="${APP_URL}/logo-mark.png" alt="" width="24" height="24" style="vertical-align:middle;display:inline-block;border:0;margin-right:8px;width:24px;height:24px;" />
          <img src="${APP_URL}/logo-text.png" alt="PersonaLink" height="22" style="vertical-align:middle;display:inline-block;border:0;height:22px;width:auto;" />
        </span>
      </div>
      <p style="margin:16px 0 0;color:rgba(255,255,255,0.85);font-size:14px;">Your ${body.windowDays}-day growth report</p>
    </div>
    <div style="padding:32px;">
      <h1 style="margin:0 0 16px;font-size:20px;font-weight:600;color:#0f172a;line-height:1.4;">${body.headline}</h1>
      ${attributionHtml}
      ${recoveryHtml}
      <div style="border-left:3px solid ${accent};padding:10px 16px;margin:0 0 24px;background:#f8fafc;border-radius:0 8px 8px 0;">
        <p style="margin:0;font-size:14px;color:#0f172a;">${body.scoreLine}</p>
      </div>
      <a href="${APP_URL}${body.cta.href}" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-bottom:16px;">${body.cta.label} →</a>
      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">Sent weekly by PersonaLink. Numbers are best-effort from LinkedIn and reflect trends, not exact UI figures.</p>
    </div>
  </div>
</body>
</html>`,
    text: [
      body.headline,
      body.attribution ?? '',
      body.recovery ?? '',
      body.scoreLine,
      '',
      `${body.cta.label}: ${APP_URL}${body.cta.href}`,
    ].filter(Boolean).join('\n\n'),
  })
}
