'use client'

import { Card, CardContent } from '@/components/ui/card'

type StepImageBriefProps = {
  firstPillar: string
}

export function StepImageBrief({ firstPillar }: StepImageBriefProps) {
  const prompts = [
    `At your desk or workspace — showing your setup and how you think`,
    `A whiteboard or notebook with your ${firstPillar || 'key idea'} framework`,
    `You in a meeting or on a call — candid, natural`,
    `Walking outdoors — candid shot that shows you as a real person`,
    `Screenshot of a result or metric you're proud of this month`,
  ]

  return (
    <>
      <div className="flex flex-col gap-3.5 mb-8">
        {prompts.map((prompt, i) => (
          <Card key={i}>
            <CardContent className="py-4 px-5 flex gap-4 items-start">
              <div className="w-7 h-7 bg-brand-light rounded-lg flex items-center justify-center text-[13px] font-bold text-brand shrink-0">{i + 1}</div>
              <p className="text-sm text-slate-600 leading-relaxed">{prompt}</p>
            </CardContent>
          </Card>
        ))}
      </div>
      <div className="text-[13px] text-slate-500 bg-slate-50 rounded-xl px-4 py-3.5 border border-slate-200">
        💡 Standard and Pro plans get a fresh, personalised image brief generated by AI every month.
      </div>
    </>
  )
}
